name: Black Cedar Organics
favicon: null
layout_spectrum: 0.95773
typography_spectrum: 0.52795
title: Herbal Infused Botanicals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71732993-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#f0f0f0'
    - '#777576'
    - '#979596'
    - '#b9b7b8'
  brandStrength: 0.05669433530420065
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
